changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - president-not-sure
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"